apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: workshop-alerts
  namespace: observability
  labels:
    release: monitor
spec:
  groups:
  - name: api.rules
    rules:
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.02
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: ">2% d’erreurs 5xx sur 10m"
        description: "Le taux d'erreurs 5xx est supérieur à 2% depuis 10 minutes."
    - alert: PodHighRestarts
      expr: increase(kube_pod_container_status_restarts_total[10m]) > 5
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Redémarrages anormaux des pods"
        description: "Plus de 5 redémarrages de conteneurs détectés dans les 10 dernières minutes."
