apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: observability
  labels:
    release: monitor
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
    - workshop
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
